// Diccionario Maestro de Actos SIR - ORIP Barranquilla 2026
const DICCIONARIO_SIR = {
    "1": { acto: "VENTA", tarifa: "CON CUANTIA", folios: "NO" },
    "2": { acto: "HIPOTECA", tarifa: "CON CUANTIA", folios: "NO" },
    "3": { acto: "REMATE", tarifa: "CON CUANTIA", folios: "NO" },
    "4": { acto: "SUCESION", tarifa: "CON CUANTIA", folios: "NO" },
    "6": { acto: "PERMUTA", tarifa: "CON CUANTIA", folios: "NO" },
    "7": { acto: "DIVISION MATERIAL", tarifa: "SIN CUANTIA", folios: "SI" },
    "8": { acto: "CANCELACION HIPOTECA", tarifa: "SIN CUANTIA", folios: "SI" },
    "9": { acto: "PATRIMONIO DE FAMILIA", tarifa: "SIN CUANTIA", folios: "SI" },
    "10": { acto: "EMBARGO", tarifa: "SIN CUANTIA", folios: "SI" },
    "11": { acto: "DEMANDA", tarifa: "SIN CUANTIA", folios: "SI" },
    "12": { acto: "REPRODUCCION CONSTANCIA", tarifa: "FIJA", folios: "NO" },
    "13": { acto: "CANCELACION PATRIMONIO DE FAMILIA", tarifa: "SIN CUANTIA", folios: "SI" },
    "14": { acto: "PROPIEDAD HORIZONTAL", tarifa: "SIN CUANTIA", folios: "SI" },
    "15": { acto: "HIPOTECA SIN LIMITE", tarifa: "CON CUANTIA", folios: "NO" },
    "16": { acto: "ACLARACION", tarifa: "SIN CUANTIA", folios: "SI" },
    "17": { acto: "CANCELACION EMBARGO", tarifa: "SIN CUANTIA", folios: "NO" },
    "18": { acto: "AFECTACION A VIVIENDA FAMILIAR", tarifa: "SIN CUANTIA", folios: "SI" },
    "19": { acto: "MATRICULAS", tarifa: "FIJA", folios: "NO" },
    "20": { acto: "TRANS. PERMISO", tarifa: "SIN CUANTIA", folios: "SI" },
    "21": { acto: "ENGLOBE", tarifa: "SIN CUANTIA", folios: "SI" },
    "22": { acto: "CONDICION RESOLUTORIA", tarifa: "SIN CUANTIA", folios: "SI" },
    "23": { acto: "USUFRUCTO (SIN CUANTIA)", tarifa: "SIN CUANTIA", folios: "SI" },
    "24": { acto: "ADJUDICACION BALDIO (SIN CUANTIA)", tarifa: "SIN CUANTIA", folios: "NO" },
    "25": { acto: "VALORIZACION", tarifa: "SIN CUANTIA", folios: "NO" },
    "26": { acto: "CANCELACION VALORIZACION", tarifa: "SIN CUANTIA", folios: "NO" },
    "27": { acto: "DESENGLOBE", tarifa: "SIN CUANTIA", folios: "SI" },
    "28": { acto: "FIDUCIA", tarifa: "CON CUANTIA", folios: "NO" },
    "29": { acto: "COMODATO", tarifa: "SIN CUANTIA", folios: "SI" },
    "30": { acto: "CANCELACION USUFRUCTO", tarifa: "SIN CUANTIA", folios: "SI" },
    "31": { acto: "SERVIDUMBRE (CON CUANTIA)", tarifa: "CON CUANTIA", folios: "NO" },
    "32": { acto: "CANCELACION DEMANDA", tarifa: "SIN CUANTIA", folios: "NO" },
    "33": { acto: "LIQUIDACION COMUNIDAD", tarifa: "SIN CUANTIA", folios: "SI" },
    "34": { acto: "CANCELACION SERVIDUMBRE", tarifa: "SIN CUANTIA", folios: "SI" },
    "35": { acto: "DECLARACION CONSTRUCCION (CON CUANTIA)", tarifa: "CON CUANTIA", folios: "NO" },
    "36": { acto: "DACION EN PAGO", tarifa: "CON CUANTIA", folios: "NO" },
    "37": { acto: "ACLARACION DE LA CUANTIA", tarifa: "SIN CUANTIA", folios: "SI" },
    "38": { acto: "VIVIENDA DE INTERES SOCIAL", tarifa: "ESPECIAL", folios: "NO" },
    "40": { acto: "USUFRUCTO (CON CUANTIA)", tarifa: "CON CUANTIA", folios: "NO" },
    "41": { acto: "ADJUDICACION BALDIO (CON CUANTIA)", tarifa: "CON CUANTIA", folios: "NO" },
    "42": { acto: "SERVIDUMBRE (SIN CUANTIA)", tarifa: "SIN CUANTIA", folios: "SI" },
    "43": { acto: "DECLARACION CONSTRUCCION (SIN CUANTIA)", tarifa: "SIN CUANTIA", folios: "SI" },
    "44": { acto: "RESTITUCION FIDUCIA (SIN CUANTIA)", tarifa: "SIN CUANTIA", folios: "SI" },
    "45": { acto: "HIPOTECA SUSTITUCION GARANTIA (CON)", tarifa: "CON CUANTIA", folios: "NO" },
    "46": { acto: "CESION DE BIENES FISCALES (CON CUANTIA)", tarifa: "CON CUANTIA", folios: "NO" },
    "47": { acto: "RESTITUCION FIDEICOMISO (SIN CUANTIA)", tarifa: "SIN CUANTIA", folios: "SI" },
    "48": { acto: "ESCISION (CON CUANTIA)", tarifa: "CON CUANTIA", folios: "NO" },
    "49": { acto: "LIQUIDACION SOCIEDAD CONYUGAL (SIN)", tarifa: "SIN CUANTIA", folios: "SI" },
    "50": { acto: "FUSION (SIN CUANTIA)", tarifa: "SIN CUANTIA", folios: "SI" },
    "51": { acto: "CESION (SIN CUANTIA)", tarifa: "SIN CUANTIA", folios: "SI" },
    "52": { acto: "CANCELACION OFERTA DE COMPRA", tarifa: "SIN CUANTIA", folios: "SI" },
    "53": { acto: "AMPLIACION DE HIPOTECA", tarifa: "CON CUANTIA", folios: "NO" },
    "54": { acto: "CANCELACION PACTO DE RETROVENTA", tarifa: "SIN CUANTIA", folios: "SI" },
    "55": { acto: "CANCELACION POR VOLUNTAD (FIDUCIA)", tarifa: "SIN CUANTIA", folios: "SI" },
    "56": { acto: "CANCELACION POR VOLUNTAD (FIDEICOMISO)", tarifa: "SIN CUANTIA", folios: "SI" },
    "60": { acto: "RESTITUCION FIDUCIA (CON CUANTIA)", tarifa: "CON CUANTIA", folios: "NO" },
    "61": { acto: "DONACION INTERNACIONAL", tarifa: "CON CUANTIA", folios: "NO" },
    "62": { acto: "SUCESION ESPECIAL", tarifa: "CON CUANTIA", folios: "NO" },
    "63": { acto: "LIQUIDACION SOCIEDAD CONYUGAL ESPECIAL", tarifa: "SIN CUANTIA", folios: "SI" },
    "64": { acto: "TESTAMENTOS", tarifa: "FIJA", folios: "NO" },
    "65": { acto: "TRANSFERENCIA NUDA PROPIEDAD", tarifa: "CON CUANTIA", folios: "NO" },
    "66": { acto: "LIQUIDACION SOCIEDAD COMERCIAL", tarifa: "SIN CUANTIA", folios: "SI" },
    "68": { acto: "LEASING", tarifa: "CON CUANTIA", folios: "NO" },
    "69": { acto: "HIPOTECA SUSTITUCION GARANTIA (SIN)", tarifa: "SIN CUANTIA", folios: "SI" },
    "70": { acto: "CANCELACION HIPOTECA ESPECIAL", tarifa: "SIN CUANTIA", folios: "SI" },
    "71": { acto: "CANCELACION COMODATO", tarifa: "SIN CUANTIA", folios: "SI" },
    "72": { acto: "REFORMA PROPIEDAD HORIZONTAL", tarifa: "SIN CUANTIA", folios: "SI" },
    "73": { acto: "REGIMEN DE COPROPIEDAD", tarifa: "SIN CUANTIA", folios: "SI" },
    "74": { acto: "CANCEL. PROPIEDAD HORIZONTAL", tarifa: "SIN CUANTIA", folios: "SI" },
    "75": { acto: "ADMINISTRACION ANTICRETICA", tarifa: "SIN CUANTIA", folios: "SI" },
    "76": { acto: "CANCELACION CONDICION RESOLUTORIA", tarifa: "SIN CUANTIA", folios: "SI" },
    "77": { acto: "CANCELACION ADMINISTRACION ANTICRETICA", tarifa: "SIN CUANTIA", folios: "SI" },
    "78": { acto: "CANCELACION AFECTACION FAMILIAR", tarifa: "SIN CUANTIA", folios: "SI" },
    "79": { acto: "TRANSFERENCIA DE DOMINIO ANT. 31-12-90", tarifa: "FIJA", folios: "NO" },
    "80": { acto: "CESION DE BIENES FISCALES", tarifa: "SIN CUANTIA", folios: "NO" },
    "81": { acto: "VENTA IDENT. PLANOS CATASTRALES", tarifa: "CON CUANTIA", folios: "NO" },
    "82": { acto: "CONSTITUCION SOCIEDAD COMERCIAL", tarifa: "CON CUANTIA", folios: "NO" },
    "83": { acto: "CANCELACION LEASING", tarifa: "SIN CUANTIA", folios: "SI" },
    "84": { acto: "ARRENDAMIENTO", tarifa: "CON CUANTIA", folios: "NO" },
    "86": { acto: "FIDEICOMISO ESPECIAL SIN TRANSFERENCIA", tarifa: "SIN CUANTIA", folios: "SI" },
    "87": { acto: "REVOCATORIA DE TESTAMENTOS", tarifa: "FIJA", folios: "NO" },
    "88": { acto: "CANCELACION FIDUCIA", tarifa: "SIN CUANTIA", folios: "SI" },
    "89": { acto: "RESTITUCION FIDEICOMISO (CON CUANTIA)", tarifa: "CON CUANTIA", folios: "NO" },
    "90": { acto: "FIDEICOMISO CIVIL CON TRANSFERENCIA", tarifa: "CON CUANTIA", folios: "NO" },
    "91": { acto: "RESTITUCION EN FIDUCIA MERCANTIL", tarifa: "SIN CUANTIA", folios: "SI" },
    "92": { acto: "RELOTEO", tarifa: "SIN CUANTIA", folios: "SI" },
    "93": { acto: "RESCISION DE CONTRATO", tarifa: "CON CUANTIA", folios: "NO" },
    "94": { acto: "RESOLUCION DE CONTRATO", tarifa: "CON CUANTIA", folios: "NO" },
    "95": { acto: "RESCILIACION", tarifa: "CON CUANTIA", folios: "NO" },
    "96": { acto: "CONCORDATO", tarifa: "SIN CUANTIA", folios: "SI" },
    "97": { acto: "LIQUIDACION OBLIGATORIA", tarifa: "SIN CUANTIA", folios: "SI" },
    "98": { acto: "LAUDO ARBITRAL", tarifa: "SIN CUANTIA", folios: "SI" },
    "99": { acto: "INSCRIPCION FOLIO ADICIONAL", tarifa: "FIJA", folios: "N/A" },
    "100": { acto: "ESCISION (SIN CUANTIA)", tarifa: "SIN CUANTIA", folios: "SI" },
    "103": { acto: "DONACION", tarifa: "CON CUANTIA", folios: "NO" },
    "104": { acto: "COMPRAVENTA DE USUFRUCTO", tarifa: "CON CUANTIA", folios: "NO" },
    "105": { acto: "ADJUDICACION UNIDAD AGRICOLA FAMILIAR", tarifa: "SIN CUANTIA", folios: "NO" },
    "106": { acto: "CESION DE BIENES FISCALES", tarifa: "SIN CUANTIA", folios: "NO" },
    "107": { acto: "EXTINCION DERECHO DOMINIO PRIVADO", tarifa: "SIN CUANTIA", folios: "SI" },
    "108": { acto: "REVERSIÓN DEL BALDÍO", tarifa: "SIN CUANTIA", folios: "NO" },
    "109": { acto: "REVOCATORIA ADMINISTRATIVA", tarifa: "SIN CUANTIA", folios: "NO" },
    "110": { acto: "CONSTITUCION RESGUARDO INDIGENA", tarifa: "EXENTO", folios: "NO" },
    "111": { acto: "AMPLIACIÓN RESGUARDO INDÍGENA", tarifa: "EXENTO", folios: "NO" },
    "112": { acto: "TITULACIÓN DE LA POSESIÓN", tarifa: "SIN CUANTIA", folios: "SI" },
    "113": { acto: "INICIO DILIGENCIAS ADMINISTRATIVAS", tarifa: "SIN CUANTIA", folios: "NO" },
    "114": { acto: "INICIO EXPROPIACION EXTINCION", tarifa: "SIN CUANTIA", folios: "NO" },
    "115": { acto: "OFERTA DE COMPRA EN BIEN RURAL", tarifa: "SIN CUANTIA", folios: "SI" },
    "116": { acto: "DESLINDE TERRENOS NACION", tarifa: "SIN CUANTIA", folios: "NO" },
    "117": { acto: "PROCESO CLARIFICACION VIGENCIA", tarifa: "SIN CUANTIA", folios: "NO" },
    "118": { acto: "IDENTIDAD REGISTRAL PREDIO BALDIO", tarifa: "SIN CUANTIA", folios: "SI" },
    "119": { acto: "INICIO PROCESO ORDENAMIENTO SOCIAL", tarifa: "SIN CUANTIA", folios: "NO" },
    "120": { acto: "LIQUIDACION SOCIEDAD CONYUGAL (CON)", tarifa: "CON CUANTIA", folios: "NO" },
    "121": { acto: "LOTEO", tarifa: "SIN CUANTIA", folios: "SI" },
    "122": { acto: "PROHIBICION DE FRACCIONAMIENTO", tarifa: "SIN CUANTIA", folios: "SI" },
    "123": { acto: "PROHIBICION DE TRANSFERENCIA", tarifa: "SIN CUANTIA", folios: "SI" },
    "124": { acto: "PROHIBICION DE APORTAR A SOCIEDADES", tarifa: "SIN CUANTIA", folios: "SI" },
    "125": { acto: "CANCELACION PROVIDENCIA ADMINISTRATIVA", tarifa: "SIN CUANTIA", folios: "NO" },
    "126": { acto: "ADJUDICACION BALDIOS COMUNIDADES NEGRAS", tarifa: "EXENTO", folios: "NO" },
    "127": { acto: "ADJUDICACION BALDIOS RESGUARDOS INDIGENAS", tarifa: "EXENTO", folios: "NO" },
    "128": { acto: "CESION TITULO GRATUITO BIENES FISCALES", tarifa: "EXENTO", folios: "NO" },
    "129": { acto: "REVOCACION ADJUDICACION BALDIOS", tarifa: "SIN CUANTIA", folios: "NO" },
    "130": { acto: "INICIO EXPROPIACION VIA ADMIN", tarifa: "SIN CUANTIA", folios: "NO" },
    "131": { acto: "INICIO EXTINCION DOMINIO", tarifa: "SIN CUANTIA", folios: "NO" },
    "132": { acto: "INICIO REVOCATORIA BALDIO", tarifa: "SIN CUANTIA", folios: "NO" },
    "133": { acto: "INICIO CONDICION RESOLUTORIA", tarifa: "SIN CUANTIA", folios: "NO" },
    "134": { acto: "INICIO CADUCIDAD ADMINISTRATIVA", tarifa: "SIN CUANTIA", folios: "NO" },
    "135": { acto: "ADJUDICACION BALDIOS A ENTIDAD PUBLICA", tarifa: "SIN CUANTIA", folios: "NO" },
    "136": { acto: "IDENTIFICACION TERRENO BALDIO", tarifa: "SIN CUANTIA", folios: "SI" },
    "137": { acto: "RECTIFICACION DE AREA Y LINDEROS", tarifa: "SIN CUANTIA", folios: "SI" },
    "138": { acto: "CONSTITUCION FIDEICOMISO CIVIL SIN CUANTIA", tarifa: "SIN CUANTIA", folios: "SI" },
    "139": { acto: "CIERRE PROCEDIMIENTO ADMINISTRATIVO", tarifa: "SIN CUANTIA", folios: "SI" },
    "146": { acto: "RATIFICACION", tarifa: "SIN CUANTIA", folios: "SI" },
    "150": { acto: "ADJUDICACIONES DE INMUEBLES RURALES", tarifa: "SIN CUANTIA", folios: "NO" },
    "151": { acto: "TRANSFERENCIA DE INMUEBLES UAF", tarifa: "SIN CUANTIA", folios: "NO" },
    "152": { acto: "TRANSFERENCIA INMUEBLES ZONAS ALTO RIESGO", tarifa: "SIN CUANTIA", folios: "NO" },
    "153": { acto: "DECLARATORIA PREDIO SALIO DOMINIO", tarifa: "SIN CUANTIA", folios: "SI" },
    "154": { acto: "PROTECCION PROVISIONAL POSESION", tarifa: "SIN CUANTIA", folios: "NO" },
    "155": { acto: "TRANSFERENCIA DE DOMINIO BIENES FISCALES", tarifa: "CON CUANTIA", folios: "NO" },
    "156": { acto: "EXPROPIACION", tarifa: "CON CUANTIA", folios: "NO" },
    "157": { acto: "AUTORIZACION ENAJENAR BIEN MENOR", tarifa: "SIN CUANTIA", folios: "SI" },
    "185": { acto: "DECLARATORIA SANEAMIENTO AUTOMATICO", tarifa: "SIN CUANTIA", folios: "SI" },
    "200": { acto: "ACTUALIZACION DE NOMENCLATURA", tarifa: "SIN CUANTIA", folios: "SI" },
    "201": { acto: "INSCRIPCION DE OFERTA", tarifa: "SIN CUANTIA", folios: "SI" },
    "202": { acto: "DACION EN PAGO ESPECIAL", tarifa: "SIN CUANTIA", folios: "NO" },
    "203": { acto: "PACTO RETROVENTA", tarifa: "SIN CUANTIA", folios: "SI" },
    "204": { acto: "CANCELACION ARRENDAMIENTO", tarifa: "SIN CUANTIA", folios: "SI" },
    "210": { acto: "HIPOTECA ESPECIAL", tarifa: "ESPECIAL", folios: "NO" },
    "250": { acto: "FUSION (CON CUANTIA)", tarifa: "CON CUANTIA", folios: "NO" },
    "251": { acto: "CESION (CON CUANTIA)", tarifa: "CON CUANTIA", folios: "NO" },
    "300": { acto: "ESTAMPILLA", tarifa: "SIN CUANTIA", folios: "NO" },
    "369": { acto: "DERECHO DE PREFERENCIA", tarifa: "SIN CUANTIA", folios: "SI" },
    "474": { acto: "REGISTRO UNICO PREDIOS ABANDONADOS", tarifa: "SIN CUANTIA", folios: "NO" },
    "501": { acto: "CONTRATO DE DERECHO DE USO", tarifa: "CON CUANTIA", folios: "NO" },
    "555": { acto: "DEPURACION", tarifa: "SIN CUANTIA", folios: "SI" },
    "619": { acto: "DECLARATORIA POSESION REGULAR", tarifa: "SIN CUANTIA", folios: "SI" },
    "777": { acto: "VARIOS", tarifa: "SIN CUANTIA", folios: "SI" },
    "843": { acto: "CANCELACION PROHIBICION TRANSFERENCIA", tarifa: "EXENTO", folios: "NO" },
    "888": { acto: "OTROS", tarifa: "SIN CUANTIA", folios: "SI" },
    "903": { acto: "ACTUALIZACION DE AREA Y/O LINDEROS", tarifa: "SIN CUANTIA", folios: "SI" },
    "906": { acto: "CAMBIO DE NOMBRE", tarifa: "SIN CUANTIA", folios: "SI" },
    "907": { acto: "CAMBIO DE RAZON SOCIAL", tarifa: "SIN CUANTIA", folios: "SI" },
    "913": { acto: "DECLARACION PARTE RESTANTE", tarifa: "SIN CUANTIA", folios: "SI" },
    "925": { acto: "DECLARACION EXTINCION OBLIGACION HIP", tarifa: "SIN CUANTIA", folios: "SI" },
    "957": { acto: "CESION POSICION CONTRACTUAL FIDUCIARIO", tarifa: "SIN CUANTIA", folios: "SI" },
    "960": { acto: "CERTIFICACION TECNICA DE OCUPACION", tarifa: "SIN CUANTIA", folios: "SI" },
    "1013": { acto: "TRANSFERENCIA DE DOMINIO TITULO CESION", tarifa: "CON CUANTIA", folios: "NO" }
};